from tkinter import *
import smtplib
from tkinter.font import *
from tkinter.scrolledtext import ScrolledText
import tkinter.ttk as t
window = Tk()
window.config(bg="black")
window.title("Email Spamming System")
titlefont = Font(size=25, underline=True, family="Courier New")
contentfont = Font(size=15,family="Times New Roman")
buttonfont = Font(size=10)
def spam():
	ct = content_input.get('1.0',END)
	server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
	server.login('thequizlol3636@gmail.com', 'redaxe3636')
	am = Amount_Scale.get()
	for i in range(am):
		server.sendmail(Input_Username.get(), Input_Victim.get(), ct)
		if int(i/am*100)<10:
			print(int(i/am*100),"%","   ","(",i,"/",am," ","mail sent.)")
		else:
			print(int(i/am*100),"%","  ","(",i,"/",am," ","mail sent.)")
	Done = Label(window, text="DONE", bg="black",fg="green",font=contentfont)
	print("100%","  ","(",am,"/",am," ","mail sent.)")
	space4.grid(row=11,column=0,columnspan=2)
	Done.grid(row=12, column=1)
	server.quit()
Username = Label(window, text="Username:",fg="white", bg="black",font=contentfont)
Input_Username = Entry(window, width=100)
Password = Label(window, text="Password:", fg="white", bg="black",font=contentfont)
Input_Password = Entry(window, width=100)
Victim = Label(window, text="Victim:", fg="white", bg="black",font=contentfont)
Input_Victim = Entry(window, width=100)
tit = Label(window, text="Email Spamming System",font=titlefont,fg="white",bg="black")
Amount = Label(window, text="Amount:", fg="white", bg="black",font=contentfont)
Amount_Scale = Scale(window, from_=1, to=80, orient=HORIZONTAL, width=5,length=600)
content = Label(window, text="Content:",bg="black",fg="white",font=contentfont)
content_input = ScrolledText(window)
space = Label(window,bg="black")
space2 = Label(window,bg="black")
space4 = Label(window,bg="black")
Submit = Button(window, text="SUBMIT", command=spam, bg="white", fg="black", font=buttonfont, pady=10,padx=30)
tit.grid(row=0,column=0,columnspan=2)
Username.grid(row=1, column=0)
Input_Username.grid(row=1, column=1)
Password.grid(row=2, column=0)
Input_Password.grid(row=2, column=1)
Victim.grid(row=3, column=0)
Input_Victim.grid(row=3, column=1)
Amount.grid(row=4,column=0)
Amount_Scale.grid(row=4,column=1)
space2.grid(row=5,column=0,columnspan=2)
content.grid(row=6,column=0)
content_input.grid(row=6,column=1)
space.grid(row=7,column=0,columnspan=2)
Submit.grid(row=8,column=1)
Input_Victim.insert(0,"melvinchia623600@gmail.com")
Input_Username.insert(0,"redaxe3636@gmail.com")
Input_Password.insert(0,"redaxe3636")
window.mainloop()
